# Generated by Django 5.1.1 on 2024-09-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=50, unique=True)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
    ]
